-- Tabla Usuarios
CREATE TABLE USUARIOS (
    USUARIOID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DOCUMENTO VARCHAR(25) NOT NULL,
    FECHANACIMIENTO DATE NOT NULL,
    GENEROID INT NOT NULL,
    CORREOELECTRONICO VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL,
    OCUPACION VARCHAR(50),
    NUMEROTELEFONO VARCHAR(20) NOT NULL,
    DIRECCIONID INT NOT NULL
);

-- Tabla Generos
CREATE TABLE GENEROS (
    GENEROID INT PRIMARY KEY AUTO_INCREMENT,  
    DESCRIPCION VARCHAR(30) 
);

-- Tabla InformacionSalud
CREATE TABLE INFORMACIONSALUD (
    INFORMACIONSALUDID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIOID INT NOT NULL,
    TIPOSANGRE VARCHAR(5) NOT NULL,
    ALERGIAS VARCHAR(200),
    CONDICIONESMEDICAS VARCHAR(200),
    MEDICAMENTOS VARCHAR(500)

);

-- Tabla Paises
CREATE TABLE PAISES (
    PAISID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(60) NOT NULL
);

-- Tabla Estados
CREATE TABLE ESTADOS (
    ESTADOID INT PRIMARY KEY AUTO_INCREMENT,
    PAISID INT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL
    
);

-- Tabla Ciudades
CREATE TABLE CIUDADES (
    CIUDADID INT PRIMARY KEY AUTO_INCREMENT,
    ESTADOID INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL
);

-- Tabla Direccion
CREATE TABLE DIRECCION (
    DIRECCIONID INT PRIMARY KEY AUTO_INCREMENT,
    CALLE VARCHAR(100),
    PAISID INT NOT NULL,
    ESTADOID INT NOT NULL,
    CIUDADID INT NOT NULL,
    CODIGOPOSTAL VARCHAR(20)
);

-- Tabla GrupoFamiliar
CREATE TABLE GRUPOFAMILIAR (
    GRUPOFAMILIARID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBREGRUPO VARCHAR(100) NOT NULL
);

-- Tabla MiembroGrupoFamiliar
CREATE TABLE MIEMBROGRUPOFAMILIAR (
    MIEMBROGRUPOFAMILIARID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIOID INT NOT NULL,
    RELACION VARCHAR(20)
);

-- Tabla MensajeAlerta
CREATE TABLE MENSAJEALERTA (
    MENSAJEALERTAID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIOID INT NOT NULL,
    GRUPOFAMILIARID INT NOT NULL,
    MENSAJE VARCHAR(500),
    FECHAHORA DATETIME
);

-- Tabla SaldoMovil
CREATE TABLE SALDOMOVIL (
    SALDOMOVILID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIOID INT NOT NULL,
    OPERADOR VARCHAR(50),
    SALDO DECIMAL(10, 2)
);

-- Tabla UbicacionUsuario
CREATE TABLE UBICACIONUSUARIO (
    USUARIOID INT PRIMARY KEY,
    LATITUD DECIMAL(10, 8) NOT NULL,
    LONGITUD DECIMAL(11, 8) NOT NULL,
    FECHAHORA DATETIME NOT NULL
);

-- Vistas
CREATE VIEW VISTAPAISES AS
    SELECT
        DISTINCT NOMBRE
    FROM
        PAISES;

CREATE VIEW VISTAESTADOS AS
    SELECT
        E.ESTADOID,
        E.NOMBRE   AS NOMBREESTADO,
        P.NOMBRE   AS NOMBREPAIS
    FROM
        ESTADOS E
        JOIN PAISES P
        ON E.PAISID = P.PAISID;

CREATE VIEW VISTACIUDADES AS
    SELECT
        C.CIUDADID,
        C.NOMBRE       AS NOMBRECIUDAD,
        E.NOMBREESTADO
    FROM
        CIUDADES     C
        JOIN VISTAESTADOS E
        ON C.ESTADOID = E.ESTADOID;

-- Procedimientos almacenados
CREATE PROCEDURE INSERTARPAIS(
    IN NOMBREPAIS VARCHAR(60)
)
BEGIN
    IF NOT EXISTS (
        SELECT
            1
        FROM
            PAISES
        WHERE
            NOMBRE = NOMBREPAIS
    ) THEN
        INSERT INTO PAISES (
            NOMBRE
        ) VALUES (
            NOMBREPAIS
        );
    END IF;

    SELECT
        PAISID,
        NOMBRE
    FROM
        PAISES
    WHERE
        NOMBRE = NOMBREPAIS;
END;

CREATE PROCEDURE INSERTARESTADO(IN NOMBREESTADO VARCHAR(50), IN PAISID INT)
BEGIN
    IF NOT EXISTS (
        SELECT
            1
        FROM
            ESTADOS
        WHERE
            NOMBRE = NOMBREESTADO
            AND PAISID = PAISID
    ) THEN
        INSERT INTO ESTADOS (
            NOMBRE,
            PAISID
        ) VALUES (
            NOMBREESTADO,
            PAISID
        );
    END IF;

    SELECT
        ESTADOID,
        NOMBRE
    FROM
        ESTADOS
    WHERE
        NOMBRE = NOMBREESTADO
        AND PAISID = PAISID;
END;

CREATE PROCEDURE INSERTARCIUDAD(IN NOMBRECIUDAD VARCHAR(50), IN ESTADOID INT)
BEGIN
    IF NOT EXISTS (
        SELECT
            1
        FROM
            CIUDADES
        WHERE
            NOMBRE = NOMBRECIUDAD
            AND ESTADOID = ESTADOID
    ) THEN
        INSERT INTO CIUDADES (
            NOMBRE,
            ESTADOID
        ) VALUES (
            NOMBRECIUDAD,
            ESTADOID
        );
    END IF;

    SELECT
        CIUDADID,
        NOMBRE
    FROM
        CIUDADES
    WHERE
        NOMBRE = NOMBRECIUDAD
        AND ESTADOID = ESTADOID;
END;
DELIMITER $$ 
CREATE PROCEDURE `INSERTARESTADO`(IN NOMBREESTADO VARCHAR(50), IN PAISID INT)
BEGIN 
	IF NOT EXISTS (SELECT 1 FROM estados WHERE estados.NOMBRE = NOMBREESTADO AND estados.PAISID = PAISID)
		INSERT INTO estados(estados.NOMBRE, estados.PAISID) VALUES (NOMBREESTADO, PAISID);
	END IF;
	SELECT estados.ESTADOID, estados.NOMBRE FROM estados WHERE estados.NOMBRE = NOMBREESTADO AND estados.PAISID = PAISID;
END$$

DELIMITER ;

DELIMITER $$